name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npx ng build --configuration production --base-href /landing_page/

      - name: Debug Build Output
        run: ls -la dist/


      - name: Prepare Files for Deployment
        run: |
          mkdir -p dist/hugo-frontend-deploy
          cp -r dist/hugo-frontend/browser/. dist/hugo-frontend-deploy/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/hugo-frontend-deploy
          publish_branch: gh-pages
          enable_jekyll: false
