name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install Dependencies
        run: npm install

      - name: Check repo structure before build
        run: ls -la

      - name: Build Angular App
        run: npx ng build --configuration production

      - name: Verify Build Output
        run: |
          if [ -d "dist/hugo-frontend" ]; then
            echo "✅ Build successful! Contents of dist/hugo-frontend:"
            ls -la dist/hugo-frontend
          else
            echo "❌ Build failed or dist/hugo-frontend does not exist."
            exit 1
          fi
      - name: Check build output
        run: ls -la dist/hugo-frontend || echo "Build folder not found!"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/hugo-frontend
          publish_branch: gh-pages
          enable_jekyll: false
